name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Update permission 1
        run: git update-index --chmod=+x ./gradlew setupCiWorkspace
      - name: Update permission 2
        run: git update-index --chmod=+x ./gradlew build
      - name: Build
        run: ./gradlew setupCiWorkspace && ./gradlew build
      - name: Rename build artifacts
        run: mv build/libs/LiquidBounce-plus.jar build/libs/lbplus-${{ github.event.head_commit.id }}.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LiquidBouncePlus
          path: build/libs/lbplus-${{ github.event.head_commit.id }}.jar
