name: build

on:
  push:
    branches: [ backup ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: clean build
          gradle-version: wrapper
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: liquidbounceplus
          path: 1.8.9-Forge/build/libs/LiquidBounce-plus.jar
